### ISSUE TITLE
Compiling restarted or error executing 'mvn install': Command failed: mvn package -f d:\Manu\Desktop\Code\Java Web\pom.xml POM file "d:\Manu\Desktop\Code\Java" specified the -f/--file command-line argument does not exist

### ISSUE THREAD

**Issue by GreenFlag31** [k-i-o/tomcatmavenhelper#1]
Hi.

New to java, maven, and just configured the community server connectors. My "hello world" is correctly displayed in the browser.

I try to use your hotreload but got the error in title when saving.

Need an extra configuration step?

THank

**Comment by k-i-o** [comment]
i think that you are open the project wrongly or just your pom.xml isn't in the right folder, send a screenshot of your folders structure pls

**Comment by GreenFlag31** [comment]
Thank you for your quick response.
Here is the structure : 
![image](https://github.com/k-i-o/tomcatmavenhelper/assets/84795623/bb4d42b0-b511-4ffa-88fc-51b7f4f1dc6e)

**Comment by k-i-o** [comment]
ok try to open "demo" with vscode and try again, maybe a future update can be that the extension search the pom.xml and define with is the project folder idk.

btw, are you italian?

**Comment by GreenFlag31** [comment]
If I open vs code with the top 'demo' folder, I don't have any view on the server connector and thus cannot instantiate a local connection.
![image](https://github.com/k-i-o/tomcatmavenhelper/assets/84795623/e7c09c66-856d-45a8-8141-581f732092dd)

I also tried cd demo (with the previous path), then triggered a saving, but I got the same error : / 

No, not italian, but I know Italy well, it's the country I have visited the most (:

**Comment by k-i-o** [comment]
okk, the server connector is just hidden, F1 and search for it or just right click on the explorer and you should click is if its appear, if its doesn't work write to me on discord: everestkio

**Comment by GreenFlag31** [comment]
added you on discord.
I have opened on 'demo' folder, but still got the same error.
![image](https://github.com/k-i-o/tomcatmavenhelper/assets/84795623/ff7dd33f-d80b-487b-91d6-703364279b5b)


Compiling restarted or error executing 'mvn install': Command failed: mvn package -f d:\Manu\Desktop\Code\Java Web\demo\pom.xml POM file "d:\Manu\Desktop\Code\Java" specified the -f/--file command-line argument does not exist

=> now correctly on mvn package -f d:\Manu\Desktop\Code\Java Web\demo\pom.xml POM file, but the error seems to be the second arg.

**Comment by GreenFlag31** [comment]
... and it seems that the path is incorrect anyway, since I don't have a 'Java' folder there ( "d:\Manu\Desktop\Code\Java" specified the -f/--file command-line argument does not exist). Correct path is : D:\Manu\Desktop\Code\Java Web\demo


Does your extention split the content at a space character? Why stopping at " D:\Manu\Desktop\Code\Java" ?

**Comment by k-i-o** [comment]
> ... and it seems that the path is incorrect anyway, since I don't have a 'Java' folder there ( "d:\Manu\Desktop\Code\Java" specified the -f/--file command-line argument does not exist). Correct path is : D:\Manu\Desktop\Code\Java Web\demo
> 
> Does your extention split the content at a space character? Why stopping at " D:\Manu\Desktop\Code\Java" ?

no it doesn't do that but i know what do that, let me fix

**Comment by k-i-o** [comment]
https://github.com/k-i-o/tomcatmavenhelper/commit/50fbb6561be82b5117a6c551fdf1d3a27127e71f that is the fix
